#!/bin/bash

ROTATE=10
CLASSIFIER="default"
OUTPUTDIR=/home/filestorotate/

for i in "$@"
do
case $i in
    -f=*|--classifier=*)
    CLASSIFIER="${i#*=}"
    shift # past argument=value
    ;;
    -r=*|--rotate=*)
    ROTATE="${i#*=}"
    shift # past argument=value
    ;;
    -o=*|--output=*)
    OUTPUTDIR="${i#*=}"
    shift # past argument=value
    ;;
    -h|--help)
    echo "Usage: dumprotate2 [-options]"
    echo "where options include:"
    echo "	-f | --classifier	project name for exemple (will be a root directory for all your dumps)"
    echo "	-r | --rotate		rotate counter (e.g: -r='10', default: $ROTATE)"
    echo "	-o | --output		output directory, location where dumps will be stored (e.g: -o='/home/filestorotate')"
    echo "	-h | --help		shows this help"
    exit 0
    ;;
    *)
          # unknown option
    ;;
esac
done

if [[ ! $ROTATE =~ ^[0-9]+$ ]]; then
      echo "Error: -r=*|--rotate=* parameter must be a number" && exit 1
fi

echo "======= START"
echo "Working Directory: $OUTPUTDIR"
echo "Rotate Counter: $ROTATE"
echo "Classifier Name: $CLASSIFIER"
echo "======="

mkdir -p $OUTPUTDIR/$CLASSIFIER

counter=$(find $OUTPUTDIR/$CLASSIFIER/ -maxdepth 1 -type f | wc -l)
#echo "Dump counter: $counter"

dumps=$(ls -1 $OUTPUTDIR/$CLASSIFIER/ | sort -r)
cpt=0
for dump in $dumps
do
	((cpt+=1))
	if [ $cpt -gt $ROTATE ]
	then
		echo "REMOVE FILE $OUTPUTDIR/$CLASSIFIER/$dump"
		rm $OUTPUTDIR/$CLASSIFIER/$dump
	fi
done


echo "======= END"
